quarkus:
  swagger-ui:
    always-include: true

  kubernetes:
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  log:
    level: INFO
    category:
      "de.doubleslash":
        level: DEBUG


gameround:
  sleep:
    duration: PT3S
step:
  sleep:
    duration: PT3S
