quarkus:
  http:
    auth:
      basic: true
      policy:
        admin-policy:
          roles-allowed: admin
      permission:
        admin-permission:
          policy: admin-policy
          paths: /games/manage/*
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          admin: ${API_PASSWORD:admin}
        roles:
          admin: admin

  swagger-ui:
    always-include: true

  kubernetes:
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    env:
      mapping:
        "api_password":
          from-secret: api-user
          with-key: password
      secrets: api-user
  log:
    level: INFO
    category:
      "org.continuouspoker":
        level: DEBUG




gameround:
  sleep:
    duration: PT1S
step:
  sleep:
    duration: PT1S

persistence:
  path: pokerstate

