on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: |
          mvn --batch-mode --update-snapshots clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.group=gcr.io/${{ secrets.GCP_PROJECT }} -Dquarkus.container-image.name=${{ secrets.GCP_APP_NAME }} -Dquarkus.container-image.tag=latest

      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
      - name: Push the Docker image to GCP
        run: |
          gcloud auth configure-docker --quiet
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }}
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_APP_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APP_NAME }} \
          --platform managed \
          --allow-unauthenticated --service-account ${{ secrets.GCP_EMAIL }} \
          --set-env-vars DISABLE_SIGNAL_HANDLERS=1
